config/routes.rb
Rails.application.routes.draw do
  
  
  get 'test/index'
    
  resources :postcode, only: :show do
    collection do
      get :search
    end
  end
  
  root 'welcome#index'

end

app/models/incident.rb
class Incident
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic

  index({location_array: "2dsphere"})

end

app/models/local_auth.rb
class LocalAuth
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  
end

app/models/postcode.rb
class Postcode

  def is_gb_postcode postcode
    @response ||= perform_lookup postcode
    is_GB=false
    if @response['results'].count > 0
      @response.parsed_response['results'][0]["address_components"].each do |ac|
        if ac["short_name"] == "GB"
          is_GB=true
        end
      end
    end
    is_GB
  end

  def getLatLong
    @response ||= perform_lookup postcode

  	latlong={}
    if @response["results"].count > 0
  	  latlong = @response.parsed_response["results"][0]["geometry"]["location"]
  	end

  	latlong
  end
  
  def local_authority
    auth = nil
    
    @response ||= perform_lookup postcode
    if @response['results'].count > 0
      @response.parsed_response['results'][0]['address_components'].each do |ac|
        auths = LocalAuth.where( name: ac['long_name'])

        auth = auths[0] if auths.count > 0

      end
    end
    
    auth
  end
  
  private 
  
  def perform_lookup postcode
    url = "http://maps.google.com/maps/api/geocode/json?address="+postcode+"&sensor=false"
    @response = HTTParty.get url
  end


end

app/models/statistic.rb
class Statistic
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/postcode_controller.rb
class PostcodeController < ApplicationController
  before_filter :validate_params



  def show
  end
  
  def search
  	@postcode=params[:postcode].gsub(/\s+/, "")
  	@postcode_lat_long = @p.getLatLong
	  @incidents = Incident.
      near_sphere(location_array:[@postcode_lat_long["lng"],@postcode_lat_long["lat"]]).
      max_distance(location_array: 1.fdiv(3959)).as_json
 	
   	@incidents_severity = Hash.new(0)
   	@daysofweek = {"Monday" => 0, "Tuesday" => 0, "Wednesday" => 0,"Thursday" => 0,"Friday" => 0,"Saturday" => 0, "Sunday" => 0}
    @incidents_gender = Hash.new(0)
		@incidents_ageband = {'0-5'=>0,'6-10'=>0,'11-15'=>0,'16-20'=>0,'21-25'=>0,'26-35'=>0,'36-45'=>0,'46-55'=>0,'56-65'=>0,'66-75'=>0,'Over 75'=>0,'Data missing'=>0}
 
   	@incidents.each do |i| 
   		severity = view_context.severity_lookup(i)
   		@incidents_severity[severity] = @incidents_severity[severity] + 1

  		daysofweek_lookup_result = view_context.daysofweek_lookup(i)
   		@daysofweek[daysofweek_lookup_result] = @daysofweek[daysofweek_lookup_result] + 1 	

                vehicles = i["vehicles"].as_json
			
                vehicles.each do |v|
                  gender = view_context.gender_lookup(v)
                  @incidents_gender[gender] = @incidents_gender[gender] + 1

                  ageband = view_context.ageband_lookup(v)
                  @incidents_ageband[ageband] = @incidents_ageband[ageband] + 1
                end
   	end	
    
    @authority = @p.local_authority
    if @authority != nil
    	@authority_incidents = Statistic.where( code: @authority.code ).first.try( :value ) || 0
    	@average_incidents = Statistic.avg( :value ).round( 0 )
    
    	@most_incidents = Statistic.where( value: Statistic.max( :value ) ).first
    	@worst_authority = LocalAuth.where( code: @most_incidents.code ).first
  	end
  end

  private
  def validate_params

  	@p = Postcode.new

		if params[:postcode] == ""
			redirect_to root_path, notice: 'Please provide postcode.'
		elsif not /[[:alnum:]]/.match(params[:postcode]) 
			redirect_to root_path, notice: 'Please provide a valid postcode.'
		elsif not @p.is_gb_postcode params[:postcode].gsub(/\s+/, "")
			redirect_to root_path, notice: 'Not a valid UK address'	
  	end
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postcode_helper.rb
module PostcodeHelper

  def severity_lookup incident
    severity = case incident['accident_severity']
    when '1'
      'Fatal'
    when '2'
      'Serious'
    else
      'Minor'
    end
    severity
  end

  
  def title_for_incident incident
    severity = severity_lookup(incident)
    
    number_of_vehicles = incident['vehicles'].count
    "#{severity} accident with #{number_of_vehicles} #{'Vehicle'.pluralize(number_of_vehicles)}"
    
  end
  

  def daysofweek_lookup incident
    severity = case incident['day_of_week']
    when '1'
      'Sunday'
    when '2'
      'Monday'
    when '3'
      'Tuesday'
    when '4'
      'Wednesday'
    when '5'
      'Thursday'
    when '6'
      'Friday'
    else
      'Saturday'
    end
    severity
  end


  def gender_lookup vehicle 
    gender = case vehicle['sex_of_driver']
    when '1'
      'Male'
    when '2'
      'Female'
    when '3'
      'Not known'
    else
      'Data missing'
    end
  end

  def ageband_lookup vehicle
    agebank = case vehicle['age_band_of_driver']
    when '1'
      '0-5'
    when '2'
      '6-10'
    when '3'
      '11-15'
    when '4'
      '16-20'
    when '5'
      '21-25'
    when '6'
      '26-35'
    when '7'
      '36-45'
    when '8'
      '46-55'
    when '9'
      '56-65'
    when '10'
      '66-75'
    when '11'
      'Over 75'
    else
      'Data missing'
    end
  end
  
  def safety_average authority, incidents, average
    
    if incidents < average
      "#{authority.name} is safer than average"
    else
      "#{authority.name} is less safe than average"
    end 
  end
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Road Safe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div class="nav-wrapper">
      <div class="container">
      <span class="beta badge">BETA</span>
        <%= link_to 'Road Safe', root_path, class:'brand-logo' %>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/postcode/search.html.erb
<style>
    #map {
        height: 750px;
    }
</style>

      <div class="row">
        <div class="col s12 m8">
          <div class="card">
            <div class="card-content">
              <span class="card-title"><%= @postcode.upcase %></span>
              <p>Your postcode</p>
            </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="card">
            <div class="card-content">
              <span class="card-title"><%= @incidents.count %></span>
              <p>How many accidents?</p>
            </div>
          </div>
        </div>
      </div>
      <% if @authority != nil %>
      <div class="row">
        <div class="col s12 m12">
          <div class="card">
            <div class="card-content">
              <span class="card-title"><%= safety_average @authority, @authority_incidents, @average_incidents %></span>
              <p>There were <%= @authority_incidents.to_i %> incidents in this local authority compared with an average of <%= @average_incidents %> in authorities around the country.</p>
              <p>The least safe local authority is <%= @worst_authority.name %> with <%= @most_incidents.value.to_i %> incidents.</p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

      <% if @incidents.count > 0 %>
        <div class="row">
          <div class="col s12 m6">
            <div class="card">
              <div class="card-content">
                <%= pie_chart (@incidents_severity) %>

                <p>How severe are they?</p>
              </div>
            </div>
          </div>
          <div class="col s12 m6">
            <div class="card">
              <div class="card-content">
                <%= bar_chart (@daysofweek), discrete: true %>


                <p>When do they occur?</p>
              </div>
            </div>
          </div>
        </div>




         <div class="row">
              <div class="col s12 m6">
                <div class="card">
                  <div class="card-content">
                    <%= pie_chart (@incidents_gender) %>

                    <p>What gender were the drivers?</p>
                  </div>
                </div>
              </div>
               <div class="col s12 m6">
                <div class="card">
                  <div class="card-content">
                    <%= bar_chart (@incidents_ageband), discrete: true %>


                    <p>How old were the drivers?</p>
                  </div>
                </div>
              </div>
            </div>
     
      <% end %>
    <div class="row">
              <div class="col s12 m12">
                <div class="card">
                  <div class="card-content">
                    <div id="panel" >
                      <button onclick="toggleDisplay()">Toggle Heatmap and Crash Details</button>
                    </div>
                    <div id="map"></div>
                  </div>
                </div>
              </div>
            </div>







<script src="https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=visualization&callback=initialize"></script>

<script>

<%- locations = [] %>
<%- @incidents.each do |i| %>
  <%- locations.append( "{
   location:{ lat: #{i['location_array']['coordinates'][1]}, lng: #{i['location_array']['coordinates'][0]} },
   label: '#{title_for_incident i}'
  }".html_safe ) %>
<%- end %>


var locationArray = [<%= locations.join(',').html_safe %>]

var redCar =  '<%= image_path("RedCar.png") %>';
var amberCar = '<%= image_path("AmberCar.png") %>'
var greenCar = '<%= image_path("GreenCar.png") %>'

var arrayOfPoints = [];
var markers = [];
var markersShown = true;

var map, heatmap;

    function initialize() {
        InitMapWithData(<%= @postcode_lat_long['lat'] %>, <%= @postcode_lat_long['lng'] %>, 2000, locationArray)
    }

    function InitMapWithData (latitude, longitude, radius, pins) {
        var center = {lat: latitude, lng: longitude};

        map = new google.maps.Map(document.getElementById('map'), {
            zoom: 14,
            center: center
        });

        var marker = new google.maps.Marker({
            position: center,
            map: map
        });

        var dataCircle = new google.maps.Circle({
          strokeColor: '#FF0000',
          strokeOpacity: 0.8,
          strokeWeight: 2,
          fillColor: '#FF0000',
          fillOpacity: 0.15,
          map: map,
          center: center,
          radius: radius
        });

        for (pin in pins) {
          addMarker(pins[pin].location, pins[pin].label, map);
          arrayOfPoints.push(new google.maps.LatLng(pins[pin].location.lat, pins[pin].location.lng));
        }

        heatmap = new google.maps.visualization.HeatmapLayer({
          data: arrayOfPoints,
          map: map
        });

        heatmap.setMap(heatmap.getMap() ? null : map);

        //toggleHeatmap();
        changeRadius();

        toggleDisplay();
      }

      function toggleHeatmap() {
  heatmap.setMap(heatmap.getMap() ? null : map);
}

function toggleDisplay ()
{
  if (markersShown == true)
  {
    clearMarkers();
    markersShown = false;
  }
  else {
    showMarkers();
    markersShown = true;
  }

  toggleHeatmap();
}

      function changeGradient() {
  var gradient = [
    'rgba(0, 255, 255, 0)',
    'rgba(0, 255, 255, 1)',
    'rgba(0, 191, 255, 1)',
    'rgba(0, 127, 255, 1)',
    'rgba(0, 63, 255, 1)',
    'rgba(0, 0, 255, 1)',
    'rgba(0, 0, 223, 1)',
    'rgba(0, 0, 191, 1)',
    'rgba(0, 0, 159, 1)',
    'rgba(0, 0, 127, 1)',
    'rgba(63, 0, 91, 1)',
    'rgba(127, 0, 63, 1)',
    'rgba(191, 0, 31, 1)',
    'rgba(255, 0, 0, 1)'
  ]
  heatmap.set('gradient', heatmap.get('gradient') ? null : gradient);
}

function changeRadius() {
  heatmap.set('radius', heatmap.get('radius') ? null : 20);
}

function changeOpacity() {
  heatmap.set('opacity', heatmap.get('opacity') ? null : 0.2);
}


    // Adds a marker to the map.
    function addMarker(location, label, map) {
        // Add the marker at the clicked location, and add the next-available label
        // from the array of alphabetical characters.
        /*var marker = new google.maps.Marker({
            position: location,
            label: label,
            map: map
        });*/

        var infowindow = new google.maps.InfoWindow({
          content: label
        });

        var iconURL = "https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/car.png";

        switch (label.charAt(0)) {
          case 'F':
          {
              iconURL = redCar;
              break;
          }
          case 'S':
          {
            iconURL = amberCar;
            break;
          }
          case 'M':
          {
            iconURL = greenCar;
            break;
          }
        }

        var marker = new google.maps.Marker({
          position: location,
          map: map,
          icon: iconURL
        });
        marker.addListener('click', function() {
          infowindow.open(map, marker);
        });

        markers.push(marker);
    }

    // Sets the map on all markers in the array.
function setMapOnAll(map) {
  for (var i = 0; i < markers.length; i++) {
    markers[i].setMap(map);
  }
}

// Removes the markers from the map, but keeps them in the array.
function clearMarkers() {
  setMapOnAll(null);
}

// Shows any markers currently in the array.
function showMarkers() {
  setMapOnAll(map);
}

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

app/views/postcode/show.html.erb
<h1>Postcode#show</h1>
<p>Find me in app/views/postcode/show.html.erb</p>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Let's get started</span>
        <p>
          Tell me your postcode and I'll have a look for the road traffic incidents nearby.
        </p>
        
        <p>
          <%= form_tag(search_postcode_index_path, method: 'get') do %>
          
            <div class="row">
              <div class="input-field col s12">
                <%= text_field_tag :postcode %>
                <%= label_tag :postcode %>
              <% if flash[:notice] %>
              <br/>
                <blockquote>
                  <p class="error-text"><%= flash[:notice] %></p>
                </blockquote>
              <% end %>
              </div>
              
            </div>
  

            <div class="row">

              <div class="input-field col s12 right-align">
                <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                </button>
              </div>
            </div>
          
          <% end %>
        </p>
        
        
      </div>
    </div>
  </div>
</div>